In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from PIL import Image
%matplotlib inline
import pickle

In [4]:
ls data

df_images_120_120.pickle


In [120]:
df = pickle.load(open('./data/df_clean_all_images_120_120.pickle','rb'))

In [121]:
df.head()

imie    0    1    2    3    4    5    6    7    8  ...  14390  14391  \
1  Grodzka  149  150  149  150  149  150  149  150  150  ...    128    128   
4  Grodzka  150  151  148  147  147  145  146  148  147  ...    149    153   
5  Grodzka  151  150  151  150  151  150  149  150  149  ...     94     91   
6  Grodzka  150  150  149  150  150  150  150  150  150  ...    147    152   
7  Grodzka  149  148  147  154  149  153  147  146  156  ...    132    135   

   14392  14393  14394  14395  14396  14397  14398  14399  
1    125    125    125    122    125    128    126    148  
4    155    152    152    153    152    148    155    155  
5     87     88     88     88     90     89     93    120  
6    145    153    147    146    148    148    149    150  
7    139    139    138    133    135    122    148    147  

[5 rows x 14401 columns]

In [105]:
#checking for missing values
df

imie    0    1    2    3    4    5    6    7    8  ...  14390  \
1       Grodzka  149  150  149  150  149  150  149  150  150  ...    128   
4       Grodzka  150  151  148  147  147  145  146  148  147  ...    149   
5       Grodzka  151  150  151  150  151  150  149  150  149  ...     94   
6       Grodzka  150  150  149  150  150  150  150  150  150  ...    147   
7       Grodzka  149  148  147  154  149  153  147  146  156  ...    132   
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
3427  Kaczynski  150  150  162  154  150  147  151  154  150  ...    154   
3429  Kaczynski  150  149  149  150  150  150  150  150  150  ...    154   
3430  Kaczynski  150  150  150  150  150  150  149  151  149  ...    150   
3431  Kaczynski  149  152  148  150  147  150  149  151  152  ...    152   
3432  Kaczynski  149  152  153  153  153  152  151  151  149  ...     86   

      14391  14392  14393  14394  14395  14396  14397  14398  14399  
1       128    125    125    125    122    125    128    126    148  
4       153    155    152    152    153    152    148    155    155  
5        91     87     88     88     88     90     89     93    120  
6       152    145    153    147    146    148    148    149    150  
7       135    139    139    138    133    135    122    148    147  
...     ...    ...    ...    ...    ...    ...    ...    ...    ...  
3427    158    160    155    152    151    141    139    149    155  
3429    155    150    148    154    145    149    149    155    151  
3430    147    145    140    139    139    134    137    138    151  
3431    151    147    147    145    143    141    138    130    149  
3432     73     67     73     75     76     76     79    100     60  

[2586 rows x 14401 columns]

In [122]:
df.dropna(axis=0,inplace=True)

In [123]:
X = df.iloc[:,1:].values #independent
y = df.iloc[:,0].values

In [124]:
X.shape
#Min Max Scalling
#Xnorm = (X - minValue) / (maxValue - minValue)

(2586, 14400)

In [125]:
X.min(), X.max()

(0, 255)

In [126]:
X_norm = X/X.max()

In [127]:
X_norm.shape

(2586, 14400)

In [128]:
y

array(['Grodzka', 'Grodzka', 'Grodzka', ..., 'Kaczynski', 'Kaczynski',
       'Kaczynski'], dtype=object)

In [129]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)

LabelEncoder()

In [130]:
list(le.inverse_transform([0, 1, 2]))

['Biedron', 'Bosak', 'Duda']

In [131]:
list(le.classes_)

['Biedron',
 'Bosak',
 'Duda',
 'Grodzka',
 'Holownia',
 'Kaczynski',
 'Kalisz',
 'Komorowski',
 'Korwin-Mikke',
 'Miller',
 'Szydlo',
 'Trzaskowski',
 'Tusk']

In [132]:
y_enc = le.fit_transform(y)
y_enc

array([3, 3, 3, ..., 5, 5, 5])

In [133]:
df['imie'] = y_enc.tolist()
df

imie    0    1    2    3    4    5    6    7    8  ...  14390  14391  \
1        3  149  150  149  150  149  150  149  150  150  ...    128    128   
4        3  150  151  148  147  147  145  146  148  147  ...    149    153   
5        3  151  150  151  150  151  150  149  150  149  ...     94     91   
6        3  150  150  149  150  150  150  150  150  150  ...    147    152   
7        3  149  148  147  154  149  153  147  146  156  ...    132    135   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
3427     5  150  150  162  154  150  147  151  154  150  ...    154    158   
3429     5  150  149  149  150  150  150  150  150  150  ...    154    155   
3430     5  150  150  150  150  150  150  149  151  149  ...    150    147   
3431     5  149  152  148  150  147  150  149  151  152  ...    152    151   
3432     5  149  152  153  153  153  152  151  151  149  ...     86     73   

      14392  14393  14394  14395  14396  14397  14398  14399  
1       125    125    125    122    125    128    126    148  
4       155    152    152    153    152    148    155    155  
5        87     88     88     88     90     89     93    120  
6       145    153    147    146    148    148    149    150  
7       139    139    138    133    135    122    148    147  
...     ...    ...    ...    ...    ...    ...    ...    ...  
3427    160    155    152    151    141    139    149    155  
3429    150    148    154    145    149    149    155    151  
3430    145    140    139    139    134    137    138    151  
3431    147    147    145    143    141    138    130    149  
3432     67     73     75     76     76     79    100     60  

[2586 rows x 14401 columns]

In [134]:
y_enc

array([3, 3, 3, ..., 5, 5, 5])

In [135]:
X_norm

array([[0.58431373, 0.58823529, 0.58431373, ..., 0.50196078, 0.49411765,
        0.58039216],
       [0.58823529, 0.59215686, 0.58039216, ..., 0.58039216, 0.60784314,
        0.60784314],
       [0.59215686, 0.58823529, 0.59215686, ..., 0.34901961, 0.36470588,
        0.47058824],
       ...,
       [0.58823529, 0.58823529, 0.58823529, ..., 0.5372549 , 0.54117647,
        0.59215686],
       [0.58431373, 0.59607843, 0.58039216, ..., 0.54117647, 0.50980392,
        0.58431373],
       [0.58431373, 0.59607843, 0.6       , ..., 0.30980392, 0.39215686,
        0.23529412]])

In [101]:
np.savez('./data/data_clean_all_120_120_norm',X_norm,y_enc)

In [136]:
# save x and y in numpy zip
np.savez('./data/data_clean_all_14400_norm.npz',X_norm,y_enc)